# Generated by Django 4.2.13 on 2024-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='Пользователь', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name_en',
            field=models.CharField(default='User', max_length=20, verbose_name='Name_en'),
        ),
    ]
