# Generated by Django 4.2.13 on 2024-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_name_alter_role_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('solved', models.BooleanField(verbose_name='Solved')),
                ('created_at', models.DateTimeField(verbose_name='Created_at')),
                ('author', models.CharField(max_length=70, verbose_name='Author')),
            ],
        ),
    ]
