# Generated by Django 4.2.13 on 2024-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_items_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='cats', to='my_app.category'),
        ),
    ]
