# Generated by Django 4.2.13 on 2024-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_items_category_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
